GET http://localhost:3000/categories

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Teste",
    "description": "5"
}

###
PATCH  http://localhost:3000/categories/6
Content-Type: application/json

{
    "description": "Musicais"
}

###
DELETE   http://localhost:3000/categories/5





####
GET http://localhost:3000/videos

###
POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "Teste",
    "description": "5",
    "category_id": 100
}

###
POST http://localhost:3000/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1234

------WebKitFormBoundary1234
Content-Disposition: form-data; name="title"

Video 1
------WebKitFormBoundary1234
Content-Disposition: form-data; name="description"

Description 1
------WebKitFormBoundary1234
Content-Disposition: form-data; name="category_id"

1
------WebKitFormBoundary1234
Content-Disposition: form-data; name="file"; filename="video.mp4"
Content-Type: video/mp4

< ./video.mp4
------WebKitFormBoundary1234--



###
PATCH  http://localhost:3000/categories/6
Content-Type: application/json

{
    "description": "Musicais"
}

###
DELETE   http://localhost:3000/categories/5